### ISSUE TITLE
Add bearer auth support

### ISSUE THREAD

**Issue by mcupak** [ga4gh/data-connect#29]
Add bearer auth support for non-public search services. Something like the following:

```yaml
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```
